# application.properties
application.name=myapp
application.version=0.0.1-SNAPSHOT


# Activa la consola web de la base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de la base de datos en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto hace que las tablas se creen solas al arrancar
spring.jpa.hibernate.ddl-auto=update

#Activamos la inicialización de scripts
spring.sql.init.mode=always

#Pospone la carga de data.sql hasta que las tablas existan
spring.jpa.defer-datasource-initialization=true